version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ${APP_PATH}/${APP_DOMAIN}/${APP_FOLDER}/:/var/www/${APP_DOMAIN}
      - ${APP_PATH}/${APP_DOMAIN}/${APP_FOLDER}/current/_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 8091:80
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.${APP_NAME}.entrypoints=https"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_DOMAIN}.localhost`)"
      - "traefik.http.routers.${APP_NAME}.tls=true"
      - "traefik.http.routers.${APP_NAME}.tls.certresolver=letsEncrypt"
    depends_on:
      - app
    networks:
      - traefik-public
      - default
      - mysql

  app:
    image: getaniftywebsite/laravel:latest
    volumes:
      - ${APP_PATH}/${APP_DOMAIN}/${APP_FOLDER}/:/var/www/${APP_DOMAIN}
      - ${APP_PATH}/${APP_DOMAIN}/${APP_FOLDER}/current/_docker/app/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - traefik-public
      - default
      - mysql
      
      
  npm:
    image: node:latest
    volumes:
      - ${APP_PATH}/${APP_DOMAIN}/${APP_FOLDER}/:/var/www/${APP_DOMAIN}
    tty: true
    working_dir: /var/www/${APP_DOMAIN}/current
    ports:
      - 5173:5173
    networks:
      - traefik-public
      - default

networks:
  traefik-public:
    external: true
  mysql:
    external: true
  default: