name: Deploy Application

on:
  push:
    branches:
      - main

env:
  SERVER_NAME: server
  SERVER_HOST: 185.233.36.64
  SERVER_USERNAME: root
  SERVER_PORT: 22
  SERVER_PATH: /var/www/my.dro.psypra.com


jobs:
  create-deployment-artifacts:
    name: Create deployment artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Compile CSS and Javascript
        run: 
          npm install
          npm run prod

      - name: Configure php 8.1
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.1
          extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml

      - name: Install Composer dependencies
        run: composer install --no-dev --no-interaction --prefer-dist

      - name: Create deployment artifact
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: tar -czf "${GITHUB_SHA}".tar.gz --exclude=*.git --exclude=node_modules --exclude=tests * 

      - name: Store artifact for destribution
        uses: actions/upload-artifact@v3
        with:
          name: app-build
          path: ${{ github.sha }}.tar.gz

  prepare-release-on-servers:
    name: "Prepare release"
    runs-on: ubuntu-latest
    needs: create-deployment-artifacts
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: app-build
      - name: Upload
        uses: appleboy/scp-action@master
        with:
          host: ${SERVER_HOST}
          username: ${SERVER_USERNAME}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${SERVER_PORT}
          source: ${{ github.sha }}.tar.gz
          target: ${SERVER_PATH}/artifacts
      - name: Extract archive and create directories
        uses: appleboy/ssh-action@master
        env:
          GITHUB_SHA: ${{ github.sha }}
        with:
          host: ${SERVER_HOST}
          username: ${SERVER_USERNAME}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${SERVER_PORT}
          envs: GITHUB_SHA
          script: |
            mkdir -p "${SERVER_PATH}/releases/${GITHUB_SHA}"
            tar xzf ${SERVER_PATH}/artifacts/${GITHUB_SHA}.tar.gz -C "${SERVER_PATH}/releases/${GITHUB_SHA}"
            mkdir -p ${SERVER_PATH}/storage/{app,public,framework,logs}
            mkdir -p ${SERVER_PATH}/storage/framework/{cache,sessions,testing,views}
            chmod -R 0777 ${SERVER_PATH}/storage
