name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  cteate-deployment-atrifacts:
    name: Create deployment artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile CSS and Javascript
        run: 
          npm install
          npm run prod
